"""Add active field to Product

Revision ID: 975214e2f505
Revises: 4afd904ec8e1
Create Date: 2025-11-12 23:05:44.306816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975214e2f505'
down_revision = '4afd904ec8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default='True', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
